// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace PPAI_DSI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20231109222322_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.13");

            modelBuilder.Entity("PPAI_DSI.Entidades.CambioEstado", b =>
                {
                    b.Property<int>("idCambioEstado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("LlamadaidLlamada")
                        .HasColumnType("INTEGER");

                    b.Property<int>("_estadoEstadoId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("_fechaHoraFin")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("_fechaHoraInicio")
                        .HasColumnType("TEXT");

                    b.HasKey("idCambioEstado");

                    b.HasIndex("LlamadaidLlamada");

                    b.HasIndex("_estadoEstadoId");

                    b.ToTable("CambiosEstado");
                });

            modelBuilder.Entity("PPAI_DSI.Entidades.Cliente", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("_dniCliente")
                        .HasColumnType("INTEGER");

                    b.Property<string>("_nombreCompleto")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("_numeroCelular")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Cliente");
                });

            modelBuilder.Entity("PPAI_DSI.Entidades.Encuesta", b =>
                {
                    b.Property<int>("idEncuesta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("_descripcion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("_fechaFinVigencia")
                        .HasColumnType("TEXT");

                    b.HasKey("idEncuesta");

                    b.ToTable("Encuestas");
                });

            modelBuilder.Entity("PPAI_DSI.Entidades.Estado", b =>
                {
                    b.Property<int>("EstadoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("_nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("EstadoId");

                    b.ToTable("Estado");
                });

            modelBuilder.Entity("PPAI_DSI.Entidades.Llamada", b =>
                {
                    b.Property<int>("idLlamada")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("_clienteID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("_descripcionOperador")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("_detalleAccionRequerida")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("_duracion")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("_encuestaEnviada")
                        .HasColumnType("INTEGER");

                    b.Property<string>("_observacionAuditor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("idLlamada");

                    b.HasIndex("_clienteID");

                    b.ToTable("Llamadas");
                });

            modelBuilder.Entity("PPAI_DSI.Entidades.Pregunta", b =>
                {
                    b.Property<int>("idPregunta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("EncuestaidEncuesta")
                        .HasColumnType("INTEGER");

                    b.Property<string>("_pregunta")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("idPregunta");

                    b.HasIndex("EncuestaidEncuesta");

                    b.ToTable("Pregunta");
                });

            modelBuilder.Entity("PPAI_DSI.Entidades.RespuestaDeCliente", b =>
                {
                    b.Property<int>("idRespuestaDeCliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("LlamadaidLlamada")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("_fechaEncuesta")
                        .HasColumnType("TEXT");

                    b.Property<int>("_respuestaSeleccionadaidRespuestaPosible")
                        .HasColumnType("INTEGER");

                    b.HasKey("idRespuestaDeCliente");

                    b.HasIndex("LlamadaidLlamada");

                    b.HasIndex("_respuestaSeleccionadaidRespuestaPosible");

                    b.ToTable("RespuestaDeCliente");
                });

            modelBuilder.Entity("PPAI_DSI.Entidades.RespuestaPosible", b =>
                {
                    b.Property<int>("idRespuestaPosible")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PreguntaidPregunta")
                        .HasColumnType("INTEGER");

                    b.Property<string>("_descripcion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("_valor")
                        .HasColumnType("INTEGER");

                    b.HasKey("idRespuestaPosible");

                    b.HasIndex("PreguntaidPregunta");

                    b.ToTable("RespuestaPosible");
                });

            modelBuilder.Entity("PPAI_DSI.Entidades.CambioEstado", b =>
                {
                    b.HasOne("PPAI_DSI.Entidades.Llamada", null)
                        .WithMany("_cambiosDeEstados")
                        .HasForeignKey("LlamadaidLlamada");

                    b.HasOne("PPAI_DSI.Entidades.Estado", "_estado")
                        .WithMany()
                        .HasForeignKey("_estadoEstadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("_estado");
                });

            modelBuilder.Entity("PPAI_DSI.Entidades.Llamada", b =>
                {
                    b.HasOne("PPAI_DSI.Entidades.Cliente", "_cliente")
                        .WithMany()
                        .HasForeignKey("_clienteID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("_cliente");
                });

            modelBuilder.Entity("PPAI_DSI.Entidades.Pregunta", b =>
                {
                    b.HasOne("PPAI_DSI.Entidades.Encuesta", null)
                        .WithMany("_preguntas")
                        .HasForeignKey("EncuestaidEncuesta");
                });

            modelBuilder.Entity("PPAI_DSI.Entidades.RespuestaDeCliente", b =>
                {
                    b.HasOne("PPAI_DSI.Entidades.Llamada", null)
                        .WithMany("_respuestasDeEncuestas")
                        .HasForeignKey("LlamadaidLlamada");

                    b.HasOne("PPAI_DSI.Entidades.RespuestaPosible", "_respuestaSeleccionada")
                        .WithMany()
                        .HasForeignKey("_respuestaSeleccionadaidRespuestaPosible")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("_respuestaSeleccionada");
                });

            modelBuilder.Entity("PPAI_DSI.Entidades.RespuestaPosible", b =>
                {
                    b.HasOne("PPAI_DSI.Entidades.Pregunta", null)
                        .WithMany("_respuestas")
                        .HasForeignKey("PreguntaidPregunta");
                });

            modelBuilder.Entity("PPAI_DSI.Entidades.Encuesta", b =>
                {
                    b.Navigation("_preguntas");
                });

            modelBuilder.Entity("PPAI_DSI.Entidades.Llamada", b =>
                {
                    b.Navigation("_cambiosDeEstados");

                    b.Navigation("_respuestasDeEncuestas");
                });

            modelBuilder.Entity("PPAI_DSI.Entidades.Pregunta", b =>
                {
                    b.Navigation("_respuestas");
                });
#pragma warning restore 612, 618
        }
    }
}
